### ISSUE TITLE
Database error on Special:PendingReviews

### ISSUE THREAD

**Issue by kghbln** [enterprisemediawiki/WatchAnalytics#119]
**Issue**

After upgrading from MW 1.27 to MW 1.35 as well as to version 3.2.0 of this extension and Approved Revs in version 1.6 I get database errors. We are now on PHP 7.4 and MySQL 8.0.15.

<pre>
[YVwhneaiTeL15Llc2pRsnAAAAAg] /index.php/Special:PendingReviews Wikimedia\Rdbms\DBQueryError from line 1699 of /mediawiki/w/includes/libs/rdbms/database/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading?
</pre>

**Error**
<pre>
Error 1054: Unknown column 'l.log_user' in 'field list' (mysql.database.example.com)

Function: PendingReview::getDeletionLog

Query: SELECT l.log_id,l.log_type,l.log_action,l.log_timestamp,l.log_user,l.log_user_text,l.log_namespace,l.log_title,l.log_page,l.log_comment_id,l.log_params,l.log_deleted,c.comment_id,c.comment_text AS log_comment FROM `logging` `l` INNER JOIN `comment` `c` ON ((l.log_comment_id=c.comment_id)) WHERE l.log_title='UserName' AND l.log_namespace=2 AND l.log_timestamp>=20201015052826

AND l.log_type IN ('delete','move') ORDER BY l.log_timestamp ASC
</pre>

**Backtrace**
<pre>
#0 /mediawiki/w/includes/libs/rdbms/database/Database.php(1683): Wikimedia\Rdbms\Database->getQueryException()
#1 /mediawiki/w/includes/libs/rdbms/database/Database.php(1658): Wikimedia\Rdbms\Database->getQueryExceptionAndLog()
#2 /mediawiki/w/includes/libs/rdbms/database/Database.php(1227): Wikimedia\Rdbms\Database->reportQueryError()
#3 /mediawiki/w/includes/libs/rdbms/database/Database.php(1907): Wikimedia\Rdbms\Database->query()
#4 /mediawiki/w/includes/libs/rdbms/database/DBConnRef.php(68): Wikimedia\Rdbms\Database->select()
#5 /mediawiki/w/includes/libs/rdbms/database/DBConnRef.php(313): Wikimedia\Rdbms\DBConnRef->__call()
#6 /mediawiki/w/extensions/WatchAnalytics/includes/PendingReview.php(288): Wikimedia\Rdbms\DBConnRef->select()
#7 /mediawiki/w/extensions/WatchAnalytics/includes/PendingReview.php(116): PendingReview->getDeletionLog()
#8 /mediawiki/w/extensions/WatchAnalytics/includes/PendingReview.php(187): PendingReview->__construct()
#9 /mediawiki/w/extensions/WatchAnalytics/specials/SpecialPendingReviews.php(126): PendingReview::getPendingReviewsList()
#10 /mediawiki/w/includes/specialpage/SpecialPage.php(600): SpecialPendingReviews->execute()
#11 /mediawiki/w/includes/specialpage/SpecialPageFactory.php(635): SpecialPage->run()
#12 /mediawiki/w/includes/MediaWiki.php(307): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#13 /mediawiki/w/includes/MediaWiki.php(940): MediaWiki->performRequest()
#14 /mediawiki/w/includes/MediaWiki.php(543): MediaWiki->main()
#15 /mediawiki/w/index.php(53): MediaWiki->run()
#16 /mediawiki/w/index.php(46): wfIndexMain()
#17 {main}
</pre>

**Comment by kghbln** [comment]
Originally reported on [MediaWiki.org](https://www.mediawiki.org/wiki/Topic:Whwqx7kcynh0z12i)

**Comment by olsonjaredm** [comment]
Hi Karsten, @revansx and I ran into this issue too, me on 1.35.5. It's resolved by https://github.com/enterprisemediawiki/WatchAnalytics/pull/113 which is waiting to be merged. If you want to help you could try the changes in [this commit](https://github.com/enterprisemediawiki/WatchAnalytics/pull/113/commits/88e133da48b8398452670db38bfdd5c25710e2da) locally and comment on the pull request if it works for you.

**Comment by kghbln** [comment]
@olsonjaredm Thanks a lot for the ping and fixing the issue! As a result of the issue the usefulness of the extension for that particular wiki was revisited. As a result it was removed. Thus I cannot test at the moment.
