### ISSUE TITLE
Move this extension to the Wikimedia Git repository?

### ISSUE THREAD

**Issue by yaronkoren** [enterprisemediawiki/WatchAnalytics#124]
WatchAnalytics is a useful extension that has unfortunately suffered from a lack of attention over the last few years. It doesn't currently work with MediaWiki 1.39, and makes use of some deprecated features (see issue #123, for example). Which is unfortunate in general, and also from the perspective of Canasta (https://canasta.wiki) - we have wanted to add this extension to Canasta, but have long been worried about its lack of maintenance, and related issues like lack of translation, etc.

Very recently, @sanjay-thiyagarajan created a fork of this extension that does work with MW 1.39 - thankfully, it only required some relatively minor fixes:

https://github.com/sanjay-thiyagarajan/WatchAnalytics

This was done with the goal of getting this extension usable by Canasta - with the next hoped-for step being to copy that version of the code into the Wikimedia Git repository, and deprecating this GitHub repository.

Any thoughts? CC @jamesmontalvo3 @krisfield @revansx

**Comment by jamesmontalvo3** [comment]
Sounds good to me.

**Comment by krisfield** [comment]
No issues from me.

**Comment by yaronkoren** [comment]
Thanks, guys! I just requested the creation of this repository; I'll let you know if/when it gets created.

**Comment by somechris** [comment]
I've just created the repo in Wikimedia's Gerrit:

  https://gerrit.wikimedia.org/r/#/admin/projects/mediawiki/extensions/WatchAnalytics

**Comment by olsonjaredm** [comment]
WA has been moved: https://github.com/wikimedia/mediawiki-extensions-WatchAnalytics
Ready to close this issue

**Comment by revansx** [comment]
Hi Jared, Are you still using Meza from here (/enterprisemediawiki/) .. did you know that we are no longer supporting Meza here.. we've moved Meza to: https://github.com/nasa/meza

Ref: https://www.mediawiki.org/wiki/Meza/NASA_Technology_Report_for_MEZA_(NTR_1654188037)

and see also: https://www.mediawiki.org/wiki/Meza/Common_Test_Environment_(CTE)

Also See: https://www.mediawiki.org/wiki/Meza/Common_Test_Environment_(CTE)

**Comment by revansx** [comment]
Oh, silly me.. I see that this is for the Watch Analytics extension .. not meza.. nevermind. Cheers!
