### ISSUE TITLE
Potential bug: Remove author or other user from watchlist for page after revision?

### ISSUE THREAD

**Issue by darenwelsh** [enterprisemediawiki/WatchAnalytics#27]
I can't repeat this or prove it yet, but I suspect something might be awry with the watch feature. There were two revisions to inhibit pages in January and I didn't notice those revisions because I was not watching them and did not receive an email or Pending Review notification. I find it hard to believe I was not watching those two pages since I was watching all of the other ~100 inhibit pages. So I think we need to do some testing (on dev with the same MW and extension versions) where different people make revisions and then verify no one was removed from the watchlist.

**Comment by jamesmontalvo3** [comment]
I marked this as a bug for now. I don't think there's any mechanism in this extension to remove watchers, so this probably isn't the culprit.

**Comment by krisfield** [comment]
I have not seen this bug an it has been over 4 years since this was reported.
