### ISSUE TITLE
Getting notice when creating a new page

### ISSUE THREAD

**Issue by jamesmontalvo3** [enterprisemediawiki/WatchAnalytics#32]
On a brand-new wiki, attempting to create a new page called "Test Page", got this message:

> Notice: Trying to get property of non-object in /var/www/meza1/htdocs/wiki/extensions/WatchAnalytics/includes/PageWatchesQuery.php on line 208

**Comment by jamesmontalvo3** [comment]
This is also being carried in enterprisemediawiki/Meza1#88

**Comment by darenwelsh** [comment]
I just saw the same notice.

![image](https://cloud.githubusercontent.com/assets/6728676/9478409/634b5b04-4b3d-11e5-8f4c-b02abb30e4c9.png)

Note how the edit text field has a big block of blue.

It looks like you fixed it in the version on your personal repo, but not in the EMW repo (used by Meza1).

**Comment by jamesmontalvo3** [comment]
I fixed it on my personal fork because I did it from my phone awhile back,
which required a master branch...I'll take another look and submit a PR if
it's ready.

**Comment by jamesmontalvo3** [comment]
Closed. See enterprisemediawiki/Meza1#88 for details.
